/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostRouteRouteImport } from './routes/post/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostIndexRouteImport } from './routes/post/index'
import { Route as PostPostIdIndexRouteImport } from './routes/post/$postId/index'
import { Route as PortalDashboardIndexRouteImport } from './routes/portal/dashboard/index'

const PostRouteRoute = PostRouteRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIndexRoute = PostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostRouteRoute,
} as any)
const PostPostIdIndexRoute = PostPostIdIndexRouteImport.update({
  id: '/$postId/',
  path: '/$postId/',
  getParentRoute: () => PostRouteRoute,
} as any)
const PortalDashboardIndexRoute = PortalDashboardIndexRouteImport.update({
  id: '/portal/dashboard/',
  path: '/portal/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/post': typeof PostRouteRouteWithChildren
  '/post/': typeof PostIndexRoute
  '/portal/dashboard': typeof PortalDashboardIndexRoute
  '/post/$postId': typeof PostPostIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/post': typeof PostIndexRoute
  '/portal/dashboard': typeof PortalDashboardIndexRoute
  '/post/$postId': typeof PostPostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/post': typeof PostRouteRouteWithChildren
  '/post/': typeof PostIndexRoute
  '/portal/dashboard/': typeof PortalDashboardIndexRoute
  '/post/$postId/': typeof PostPostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/post' | '/post/' | '/portal/dashboard' | '/post/$postId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/post' | '/portal/dashboard' | '/post/$postId'
  id:
    | '__root__'
    | '/'
    | '/post'
    | '/post/'
    | '/portal/dashboard/'
    | '/post/$postId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostRouteRoute: typeof PostRouteRouteWithChildren
  PortalDashboardIndexRoute: typeof PortalDashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/': {
      id: '/post/'
      path: '/'
      fullPath: '/post/'
      preLoaderRoute: typeof PostIndexRouteImport
      parentRoute: typeof PostRouteRoute
    }
    '/post/$postId/': {
      id: '/post/$postId/'
      path: '/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdIndexRouteImport
      parentRoute: typeof PostRouteRoute
    }
    '/portal/dashboard/': {
      id: '/portal/dashboard/'
      path: '/portal/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PostRouteRouteChildren {
  PostIndexRoute: typeof PostIndexRoute
  PostPostIdIndexRoute: typeof PostPostIdIndexRoute
}

const PostRouteRouteChildren: PostRouteRouteChildren = {
  PostIndexRoute: PostIndexRoute,
  PostPostIdIndexRoute: PostPostIdIndexRoute,
}

const PostRouteRouteWithChildren = PostRouteRoute._addFileChildren(
  PostRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostRouteRoute: PostRouteRouteWithChildren,
  PortalDashboardIndexRoute: PortalDashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
